# Docker Compose override za optimizaciju Gavra aplikacije na low-spec laptop
version: '3.8'

services:
  db:
    # PostgreSQL optimizacija za 8GB RAM laptop
    environment:
      - POSTGRES_SHARED_BUFFERS=128MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=512MB  
      - POSTGRES_WORK_MEM=4MB
      - POSTGRES_MAINTENANCE_WORK_MEM=64MB
      - POSTGRES_MAX_CONNECTIONS=50
      - POSTGRES_WAL_BUFFERS=8MB
    command: >
      postgres 
      -c shared_buffers=128MB
      -c effective_cache_size=512MB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB
      -c max_connections=50
      -c wal_buffers=8MB
      -c max_wal_size=512MB
      -c min_wal_size=128MB
      -c random_page_cost=1.1
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  kong:
    # API Gateway optimizacija
    environment:
      - KONG_WORKER_PROCESSES=1
      - KONG_NGINX_WORKER_CONNECTIONS=512
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  auth:
    # Auth servis optimizacija
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  rest:
    # PostgREST optimizacija
    environment:
      - PGRST_DB_POOL=5
      - PGRST_DB_MAX_ROWS=500
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  realtime:
    # Realtime optimizacija
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  studio:
    # Studio web UI optimizacija
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'