analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/cleanup_*.js"
    - "**/debug_*.js"
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore
    unused_import: warning
    dead_code: warning
    unused_element: warning
    unnecessary_null_comparison: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Debug & Performance rules
    avoid_slow_async_io: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Code Quality rules  
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    
    # Style rules
    prefer_single_quotes: true
    # require_trailing_commas: true  # TEMPORARILY DISABLED - too many violations
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
