workflows:
  ios-workflow:
    name: Gavra Bus iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: com.gavra.gavra013
        BUNDLE_ID: com.gavra.gavra013
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up app signing
        script: |
          set -ex
          echo "App signing will be configured later"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Clean and install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod cache clean --all || true
          pod deintegrate || true
          # Ensure Flutter generated files exist before pod install
          cd ..
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Flutter build ipa
        script: |
          flutter build ios --release --no-codesign \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
