# 🍎 iOS Build Configuration
# =========================

# Build environments
environments:
  development:
    bundle_id: com.gavra013.gavraAndroid.dev
    app_name: "Gavra Bus Dev"
    firebase_config: ios/Firebase/GoogleService-Info-dev.plist
    
  staging:
    bundle_id: com.gavra013.gavraAndroid.staging
    app_name: "Gavra Bus Staging"
    firebase_config: ios/Firebase/GoogleService-Info-staging.plist
    
  production:
    bundle_id: com.gavra013.gavraAndroid
    app_name: "Gavra 013"
    firebase_config: ios/Runner/GoogleService-Info.plist

# Code signing
code_signing:
  team_id: 6CY9Q44KMQ
  certificate: "Apple Distribution"
  provisioning_profiles:
    development: "Gavra_013_Development_Profile"
    staging: "Gavra_013_AdHoc_Profile"
    production: "Gavra_013_App_Store_Profile"

# Build settings
build_settings:
  deployment_target: "12.0"
  supported_devices: "1,2"  # iPhone + iPad
  requires_full_screen: false
  
  # Capabilities
  capabilities:
    - app-groups
    - push-notifications
    - location-services
    - background-modes
    - audio

# TestFlight settings
testflight:
  beta_groups:
    - "Internal Testers"
    - "Gavra Bus Beta"
    - "Drivers"
    - "Passengers"
  
  localized_build_info:
    en-US:
      whats_new: |
        🚌 What's New in Gavra Bus:
        • Real-time bus tracking
        • Firebase integration
        • Push notifications
        • Enhanced user experience
        • Bug fixes and improvements
    sr-RS:
      whats_new: |
        🚌 Novo u Gavra Bus aplikaciji:
        • Praćenje autobusa u realnom vremenu
        • Firebase integracija
        • Push obaveštenja
        • Poboljšano korisničko iskustvo
        • Ispravke grešaka i poboljšanja
