default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV['APP_IDENTIFIER'] => ENV['PROVISIONING_PROFILE_NAME']
        }
      }
    )
    upload_to_testflight(
      api_key: {
        key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
        issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
        key_content: ENV['APP_STORE_CONNECT_API_KEY'],
        in_house: false
      }
    )
  end
end

