name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    name: Analyze and Test (${{ matrix.flutter-channel }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-channel: [stable, beta]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Install dependencies
        run: flutter pub get --verbose > pub_get.log 2>&1

      - name: Run analyzer
        run: flutter analyze --verbose > analyze.log 2>&1

      - name: Run tests
        run: flutter test --coverage --verbose > test.log 2>&1

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: flutter-ci-logs-${{ matrix.flutter-channel }}
          path: |
            pub_get.log
            analyze.log
            test.log
