name: iOS Test Build

on:
  workflow_dispatch:
  push:
    branches: [ test-ios ]

jobs:
  test-ios-build:
    runs-on: macos-13
    
    env:
      FLUTTER_VERSION: '3.24.5'
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
        
    - name: Setup Xcode
      run: |
        echo "📱 Available Xcode versions:"
        ls -la /Applications/ | grep -i xcode || true
        echo "Current Xcode:"
        xcode-select -p || true
        
        # Set up Xcode (simple approach)
        if [ -d "/Applications/Xcode.app" ]; then
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer  
          echo "✅ Using default Xcode"
        else
          echo "❌ No Xcode found!"
          exit 1
        fi
        
        xcode-select -p
        xcodebuild -version
        
    - name: Print Flutter version
      run: flutter --version
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Clean previous builds
      run: |
        flutter clean
        cd ios
        rm -rf Pods Podfile.lock build/
      
    - name: Analyze project
      run: flutter analyze --no-fatal-infos || true
      
    - name: Install CocoaPods
      run: |
        cd ios
        pod install --verbose
        
    - name: Build iOS app (no codesign)
      run: |
        echo "🔨 Building iOS app without code signing..."
        flutter build ios --release --no-codesign
        echo "✅ Flutter build completed successfully"
        
        # Check what was built
        echo "📁 Checking build output..."
        ls -la build/ios/iphoneos/
        
        if [[ -d "build/ios/iphoneos/Runner.app" ]]; then
          echo "✅ Runner.app found"
          ls -la build/ios/iphoneos/Runner.app/
          echo "📱 App bundle size: $(du -sh build/ios/iphoneos/Runner.app | cut -f1)"
        else
          echo "❌ Runner.app not found!"
          exit 1
        fi
        
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-test-build-artifacts
        path: |
          build/ios/iphoneos/Runner.app
        retention-days: 7
