name: iOS Build with Manual Signing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  build_ios:
    name: Build iOS with Manual Signing
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
    
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        
    - name: Create iOS certificate file
      run: |
        echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 --decode > ios/ios_distribution.p12
        ls -la ios/ios_distribution.p12
    
    - name: Create provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/app_store.mobileprovision
        ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
    
    - name: Create keychain and import certificate
      run: |
        # Debug certificate password secret
        echo "Testing certificate password secret access..."
        
        # Create temporary keychain
        security create-keychain -p github-actions build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p github-actions build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        
        # Try import with environment variable password
        echo "Attempting to import certificate with password..."
        security import ios/ios_distribution.p12 -k build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign -T /usr/bin/xcodebuild
        security set-key-partition-list -S apple-tool:,apple: -s -k github-actions build.keychain
        
        # Verify certificate
        security find-identity -v -p codesigning build.keychain
        
    - name: Build iOS App
      run: |
        flutter build ipa \
          --release \
          --export-method=app-store \
          --build-name=1.0.${{ github.run_number }} \
          --build-number=${{ github.run_number }}
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-${{ github.run_number }}
        path: build/ios/ipa/*.ipa
        retention-days: 30
    
    - name: Cleanup
      if: always()
      run: |
        security delete-keychain build.keychain || true
        rm -f ios/ios_distribution.p12 || true
