name: iOS Build with Manual Signing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  build_ios:
    name: Build iOS with Manual Signing
    runs-on: macos-13  # Use macOS 13 with iOS 17 support
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
    
    - name: Setup App Store Connect API
      run: |
        echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" | base64 --decode > AuthKey.p8
        
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        
    - name: Setup App Store Connect API
      run: |
        # Create App Store Connect API key file
        mkdir -p ~/private_keys
        echo "${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}" | base64 --decode > ~/private_keys/AuthKey_F4P38UR78G.p8
        echo "${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}" | base64 --decode > AuthKey_F4P38UR78G.p8
        
    - name: Build iOS App for TestFlight
      run: |
        # Set build number and name in Flutter
        flutter build ios --release --no-codesign \
          --build-name=1.0.${{ github.run_number }} \
          --build-number=${{ github.run_number }}
        
        # Use fastlane for both build and upload
        cd ios
        
        # Create simple Fastfile for build
        cat > fastlane/Fastfile << 'EOF'
        default_platform(:ios)
        platform :ios do
          desc "Build and upload to TestFlight"
          lane :build_and_upload do
            build_app(
              workspace: "Runner.xcworkspace",
              scheme: "Runner",
              configuration: "Release", 
              export_method: "app-store",
              output_directory: "./build",
              output_name: "Runner.ipa",
              xcargs: "-allowProvisioningUpdates DEVELOPMENT_TEAM=6CY9Q44KMQ"
            )
            
            pilot(
              api_key_path: "../AuthKey_F4P38UR78G.p8",
              api_key: "F4P38UR78G", 
              issuer_id: "d8b50e72-6330-401d-9aef-4ead356405ca",
              ipa: "./build/Runner.ipa",
              skip_waiting_for_build_processing: true,
              skip_submission: true,
              team_id: "6CY9Q44KMQ"
            )
          end
        end
        EOF
        
        # Install fastlane
        gem install fastlane
        
        # Run fastlane
        fastlane build_and_upload
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa-${{ github.run_number }}
        path: ios/build/*.ipa
        retention-days: 30
    
    - name: Cleanup
      if: always()
      run: |
        rm -f ios/build/*.ipa || true
