name: iOS Build with Manual Signing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  build_ios:
    name: Build iOS with Manual Signing
    runs-on: macos-13  # Use macOS 13 with iOS 17 support
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
    
    - name: Setup App Store Connect API
      run: |
        echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" | base64 --decode > AuthKey.p8
        
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        
    - name: Setup App Store Connect API
      run: |
        # Create App Store Connect API key file
        mkdir -p ~/private_keys
        echo "${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}" | base64 --decode > ~/private_keys/AuthKey_F4P38UR78G.p8
        echo "${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}" | base64 --decode > AuthKey_F4P38UR78G.p8
        
        # Import certificate and provisioning profile for manual signing
        # Create keychain
        security create-keychain -p actions build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p actions build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        
        # Import certificate
        echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 --decode > ios_distribution.p12
        security import ios_distribution.p12 -k build.keychain -P "" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k actions build.keychain
        
        # Install provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/AppStore.mobileprovision
        
    - name: Build iOS App for TestFlight
      run: |
        # Set build number and name in Flutter
        flutter build ios --release --no-codesign \
          --build-name=1.0.${{ github.run_number }} \
          --build-number=${{ github.run_number }}
        
        cd ios
        # Build using xcodebuild with manual signing
        xcodebuild archive \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath build/Runner.xcarchive \
          DEVELOPMENT_TEAM=6CY9Q44KMQ \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER="Gavra 013 App Store Profile" \
          CODE_SIGN_IDENTITY="iPhone Distribution"
        
        # Export IPA
        xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportPath build \
          -exportOptionsPlist ExportOptionsTestFlight.plist
          
    - name: Upload to TestFlight
      run: |
        # Install fastlane
        gem install fastlane
        
        cd ios
        fastlane pilot upload \
          --api_key_path "../AuthKey_F4P38UR78G.p8" \
          --api_key "F4P38UR78G" \
          --issuer_id "d8b50e72-6330-401d-9aef-4ead356405ca" \
          --ipa "build/Runner.ipa" \
          --skip_waiting_for_build_processing \
          --skip_submission \
          --team_id "6CY9Q44KMQ"
    
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa-${{ github.run_number }}
        path: build/ios/ipa/*.ipa
        retention-days: 30
    
    - name: Cleanup
      if: always()
      run: |
        security delete-keychain build.keychain || true
        rm -f ios/ios_distribution.p12 || true
