name: iOS Build with Manual Signing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  build_ios:
    name: Build iOS with Manual Signing
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
    
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        
    - name: Create iOS certificate file
      run: |
        # Skip certificate creation and use automatic signing instead
        echo "Skipping manual certificate - using automatic signing"
    
    - name: Create provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/app_store.mobileprovision
        ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
    
    - name: Create keychain and import certificate
      run: |
        echo "Skipping keychain setup - using automatic signing"
        
    - name: Build iOS App
      run: |
        flutter build ipa \
          --release \
          --build-name=1.0.${{ github.run_number }} \
          --build-number=${{ github.run_number }}
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-${{ github.run_number }}
        path: build/ios/ipa/*.ipa
        retention-days: 30
    
    - name: Cleanup
      if: always()
      run: |
        security delete-keychain build.keychain || true
        rm -f ios/ios_distribution.p12 || true
