name: Test Trigger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test
      run: |
        echo "🚀 Workflow is working!"
        echo "Current time: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
